language: php
php:
  - 5.3
before_script:
  - pear install PHP_CodeSniffer
  - wget http://ftp.drupal.org/files/projects/drupalcs-7.x-1.0-beta1.tar.gz -O ../drupalcs.tar.gz
  - tar -xvzf ../drupalcs.tar.gz -C ../
  - phpenv rehash
script: 
  - phpcs . --standard=../drupalcs/Drupal/ruleset.xml --extensions=php,module,inc,install,test,profile,theme



